inherit_from:
  - https://raw.githubusercontent.com/plataformatec/linters/master/.rubocop.yml

Style/AsciiComments:
  Enabled: true

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
